# Generated by Django 5.0.7 on 2026-04-27 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('BUSINESS_PHOTO', 'Business Photo'), ('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('SUPPLIER_NOTE', 'Supplier Note'), ('SALES_NOTE', 'Sales Note'), ('QRIS_SCREENSHOT', 'QRIS Screenshot'), ('OTHER', 'Other')], max_length=32)),
                ('source_type', models.CharField(choices=[('SELF_UPLOADED', 'Self Uploaded'), ('AGENT_ASSISTED', 'Agent Assisted'), ('AGENT_VERIFIED', 'Agent Verified')], default='SELF_UPLOADED', max_length=32)),
                ('file', models.FileField(upload_to='evidence/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('field_agent_note', models.TextField(blank=True)),
                ('ai_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='borrowers.borrowerprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('detected_business_indicators', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_result', to='evidence.evidenceitem')),
            ],
        ),
    ]
