# Generated by Django 5.0.7 on 2026-04-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_storage_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceitem',
            name='file',
            field=models.FileField(blank=True, upload_to='evidence/'),
        ),
    ]
