# Generated by Django 5.0.7 on 2026-04-27 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReadinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('readiness_band', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('PROMISING', 'Promising'), ('STRONG', 'Strong')], max_length=20)),
                ('confidence_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('positive_signals', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('main_reasons', models.JSONField(blank=True, default=list)),
                ('suggested_next_action', models.TextField(blank=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('analyst_notes', models.TextField(blank=True)),
                ('final_human_decision', models.CharField(choices=[('PENDING', 'Pending'), ('NEEDS_MORE_DATA', 'Needs More Data'), ('RECOMMENDED_FOR_REVIEW', 'Recommended For Review'), ('NOT_RECOMMENDED_AT_THIS_STAGE', 'Not Recommended At This Stage')], default='PENDING', max_length=40)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='borrowers.borrowerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InstantEvidenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_completeness_score', models.PositiveIntegerField(default=0)),
                ('evidence_quality_score', models.PositiveIntegerField(default=0)),
                ('detected_business_indicators', models.JSONField(blank=True, default=dict)),
                ('ocr_summary', models.TextField(blank=True)),
                ('business_note_summary', models.TextField(blank=True)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('weak_evidence', models.JSONField(blank=True, default=list)),
                ('recommended_next_steps', models.JSONField(blank=True, default=list)),
                ('can_submit_to_analyst', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_checks', to='borrowers.borrowerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
