# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditreadinessreview",
            name="final_human_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("NEEDS_MORE_DATA", "Needs More Data"),
                    ("RECOMMENDED_FOR_REVIEW", "Recommended For Review"),
                    ("NOT_RECOMMENDED_AT_THIS_STAGE", "Not Recommended At This Stage"),
                    ("APPROVED_FOR_FINANCING", "Approved For Financing"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
    ]
