# Generated by Django 5.0.7 on 2026-04-27 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_category', models.CharField(blank=True, max_length=120)),
                ('business_duration_months', models.PositiveIntegerField(default=0)),
                ('financing_purpose', models.TextField(blank=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_monthly_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('simple_cashflow_note', models.TextField(blank=True)),
                ('business_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONSENTED', 'Consented'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('NEEDS_COMPLETION', 'Needs Completion'), ('READY_FOR_ANALYST', 'Ready for Analyst'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_profiles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_version', models.CharField(default='v1-local-demo', max_length=40)),
                ('consent_text_snapshot', models.TextField()),
                ('data_processing_purpose', models.TextField()),
                ('ai_usage_disclosure', models.TextField()),
                ('user_rights_disclosure', models.TextField()),
                ('given_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='borrowers.borrowerprofile')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
